### ISSUE TITLE
Error after AP mode

### ISSUE THREAD

**Issue by Snyder1977** [sabhiram/raspberry-wifi-conf#14]
I am also getting an error when I try to run it on a pi 3:

`pi@raspberrypi:~/raspberry-wifi-conf $ sudo npm start

> raspberry-wifi-conf@0.0.1 start /home/pi/raspberry-wifi-conf
> node server.js

Wifi is not enabled, Enabling AP for self-configure

Force reconfigure enabled - reset AP
ifdown wlan0 successful...
ifup wlan0 successful...
... dhcp server restarted!
... hostapd restarted!
... AP Enable Success!

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at Server.listen (net.js:1138:5)
    at EventEmitter.app.listen (/home/pi/raspberry-wifi-conf/node_modules/express/lib/application.js:559:24)
    at module.exports (/home/pi/raspberry-wifi-conf/app/api.js:76:9)
    at start_http_server (/home/pi/raspberry-wifi-conf/server.js:64:32)
    at /home/pi/raspberry-wifi-conf/node_modules/async/lib/async.js:607:21
    at /home/pi/raspberry-wifi-conf/node_modules/async/lib/async.js:246:17
    at iterate (/home/pi/raspberry-wifi-conf/node_modules/async/lib/async.js:146:13)

npm ERR! raspberry-wifi-conf@0.0.1 start: `node server.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the raspberry-wifi-conf@0.0.1 start script.
npm ERR! This is most likely a problem with the raspberry-wifi-conf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls raspberry-wifi-conf
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.1.19-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/raspberry-wifi-conf
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/raspberry-wifi-conf/npm-debug.log
npm ERR! not ok code 0
pi@raspberrypi:~/raspberry-wifi-conf $ `

**Comment by Snyder1977** [comment]
Another server was running and using the same port.
The solution was to kill the process.

http://stackoverflow.com/questions/16827987/expressjs-throw-er-unhandled-error-event
