### ISSUE TITLE
Cannot find module 'async'

### ISSUE THREAD

**Issue by Mark-81** [sabhiram/raspberry-wifi-conf#17]
I installed the async module but it seems it's not enough:

$ sudo npm install async -g
/usr/lib
`-- async@2.0.0-rc.4 

$ node server.js 
module.js:440
    throw err;
    ^

Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/utils/raspberry-wifi-conf/server.js:1:89)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

What am I missing?

**Comment by Mark-81** [comment]
It seems I cannot install the modules globally.

**Comment by sabhiram** [comment]
could it be that you are running things as sudo along with the -g flag? Try launching the node app with sudo

**Comment by sabhiram** [comment]
I verified that with the latest `async` this server starts as expected. Closing this for now ...
