### ISSUE TITLE
Not able to access the HTTP server  

### ISSUE THREAD

**Issue by FernandoKelvin** [sabhiram/raspberry-wifi-conf#19]
HI, 

I have made all the steps to install and run the solution. At this point  the raspberry is working as a AP and I can connect my PC to it. But when wen I try to access the server typing http://192.168.44.1:88 on google Chromo it tells me that he is not able to connect to the address for some reason (proxy and etc..).
How can I check if my server is running on the raspberry pi? 

Thanks.

**Comment by sabhiram** [comment]
If you are SSH'd into the raspberry pi, first ensure that the node application is running. To be honest, I have not touched nodejs in the last 2 years as I have been playing mostly with Go. I reckon I still could help you troubleshoot this however.

The next thing I would do is try and curl or wget port 88 on the raspberry pi to make sure that the server is responding to local queries. The last thing to try would be to attempt to ping the Pi's IP address once you have connected to the AP. 

Let me know how that goes. Hope this helps you out!

**Comment by FernandoKelvin** [comment]
Thank for the answer Sabhiram!
Now I'm working in another project, but as soon as possible I will try what you said and I tell you.

**Comment by duelago** [comment]
I have the same problem. The node server fails to start. Everything else is up and running. It would be really nice if you can look in to this problem. Your solution is exactly what I am looking for. Keep up the good work :) 

 I get this error if I try to start the server:

root@orangepizero:/home/pi/raspberry-wifi-conf# node server.js 
/home/pi/raspberry-wifi-conf/app/wifi_manager.js:136
            info["hw_addr"].toLowerCase() == info["ap_addr"].toLowerCase() &&
                                                            ^
TypeError: Cannot read property 'toLowerCase' of undefined
    at _is_ap_enabled_sync (/home/pi/raspberry-wifi-conf/app/wifi_manager.js:136:61)
    at _is_wifi_enabled_sync (/home/pi/raspberry-wifi-conf/app/wifi_manager.js:115:28)
    at /home/pi/raspberry-wifi-conf/app/wifi_manager.js:126:35
    at /home/pi/raspberry-wifi-conf/app/wifi_manager.js:90:20
    at /home/pi/raspberry-wifi-conf/node_modules/async/lib/async.js:251:17
    at /home/pi/raspberry-wifi-conf/node_modules/async/lib/async.js:154:25
    at /home/pi/raspberry-wifi-conf/node_modules/async/lib/async.js:248:21
    at /home/pi/raspberry-wifi-conf/node_modules/async/lib/async.js:612:34
    at /home/pi/raspberry-wifi-conf/app/wifi_manager.js:76:17
    at ChildProcess.exithandler (child_process.js:742:7)

**Comment by Al85** [comment]
darland's fork work in my RPI3.

**Comment by sabhiram** [comment]
I really need to get my hands on a Pi3 to see whats up with all this. I really have been waiting for a free weekend to redo this whole thing in `golang`. But a man can dream :(

**Comment by duelago** [comment]
I tried Darland's fork on my orangepizero and the node webserver works. However, I have problems with the DHCP server used in his fork. I'm not a programmer so it is a bit difficult for me to debug this.

**Comment by benjamingauthier** [comment]
@darland's fork works with my RP3 too.

@sabhiram any idea when you'll have a free weekend ? ;)

**Comment by sabhiram** [comment]
Bah, still dreaming :) My startup has me doing 100 hour weeks so any time to rest is time either sleeping or hanging with the wife. However, this repo has seen a lot of interest lately and as soon as I have some free time I plan to redo this. Let me see about getting my hands on a Pi3 (Ill order one today) so I can at-least repro what you guys are seeing.

**Comment by sabhiram** [comment]
I have a feeling that recent versions of raspbian have messed with the dhcp stuff that I glued together. Try running this ```service isc-dhcp-server restart``` and post the output. If it fails, it might be something obvious.

**Comment by sabhiram** [comment]
Try using the latest code, there have been a few fixes needed to get this to work correctly. Also if you have `dhcpcd` installed you will need to ignore the wlan interface you are using as explained in the README.md file.

**Comment by bergsm** [comment]
I ran `service isc-dhcp-server restart` and got Access denied
